//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDATFFS.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KDATFFS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Execute &quot;{2}&quot; command occur error in &quot;{1}&quot; of &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        public static string CommandExecutionExceptionMessage {
            get {
                return ResourceManager.GetString("CommandExecutionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 can&apos;t find element by {2}=&quot;{3}&quot; method in &quot;{1}&quot; of &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        public static string FindMethodExecuteException {
            get {
                return ResourceManager.GetString("FindMethodExecuteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t recognize the &quot;{0}&quot; command in Browser types,please check Command column! 的本地化字符串。
        /// </summary>
        public static string ParseBrowserCommandExceptionn {
            get {
                return ResourceManager.GetString("ParseBrowserCommandExceptionn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t recognize the &quot;{0}&quot; command type ,please check CommandType column! 的本地化字符串。
        /// </summary>
        public static string ParseCommandTypesException {
            get {
                return ResourceManager.GetString("ParseCommandTypesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Have duplicate data in the  Sheet &quot;{0}&quot; , TestId &quot;{1}&quot; ,TestStepId &quot;{2}&quot;! 的本地化字符串。
        /// </summary>
        public static string ParseDuplicateException {
            get {
                return ResourceManager.GetString("ParseDuplicateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t recognize the &quot;{0}&quot; command in Element types,please check Command column! 的本地化字符串。
        /// </summary>
        public static string ParseElementCommandException {
            get {
                return ResourceManager.GetString("ParseElementCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t recognize the &quot;{0}&quot; findmethod type,please check FindMethodType column! 的本地化字符串。
        /// </summary>
        public static string ParseFindMethodException {
            get {
                return ResourceManager.GetString("ParseFindMethodException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t recognize the &quot;{0}&quot; command in Validate types,please check Command column! 的本地化字符串。
        /// </summary>
        public static string ParseValidateCommandException {
            get {
                return ResourceManager.GetString("ParseValidateCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        public static string StepSpacingTime {
            get {
                return ResourceManager.GetString("StepSpacingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Page Source does&apos;t contain &quot;{0}&quot; text! 的本地化字符串。
        /// </summary>
        public static string ValidateContainTextException {
            get {
                return ResourceManager.GetString("ValidateContainTextException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The actual value &quot;{1}&quot;  does&apos;t math the expected values &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        public static string ValidationExceptionRegex {
            get {
                return ResourceManager.GetString("ValidationExceptionRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The actual value &quot;{1}&quot;  does&apos;t math the expected values &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        public static string ValidationExceptionStringEquals {
            get {
                return ResourceManager.GetString("ValidationExceptionStringEquals", resourceCulture);
            }
        }
    }
}
