//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDATFFSRecorder.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KDATFFSRecorder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 access element denied! 的本地化字符串。
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 back &quot;{0}&quot;page 的本地化字符串。
        /// </summary>
        internal static string BackComment {
            get {
                return ResourceManager.GetString("BackComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 clear data in &quot;{1}&quot; of &quot;{0}&quot; page 的本地化字符串。
        /// </summary>
        internal static string ClearComment {
            get {
                return ResourceManager.GetString("ClearComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 click &quot;{1}&quot; in &quot;{0}&quot; page 的本地化字符串。
        /// </summary>
        internal static string ClickComment {
            get {
                return ResourceManager.GetString("ClickComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 close &quot;{0}&quot;page 的本地化字符串。
        /// </summary>
        internal static string CloseComment {
            get {
                return ResourceManager.GetString("CloseComment", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap csv {
            get {
                object obj = ResourceManager.GetObject("csv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap forward {
            get {
                object obj = ResourceManager.GetObject("forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 froward &quot;{0}&quot;page 的本地化字符串。
        /// </summary>
        internal static string ForwardComment {
            get {
                return ResourceManager.GetString("ForwardComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to &quot;{0}&quot;page 的本地化字符串。
        /// </summary>
        internal static string GotoComment {
            get {
                return ResourceManager.GetString("GotoComment", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap gotourl {
            get {
                object obj = ResourceManager.GetObject("gotourl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Known Bug 的本地化字符串。
        /// </summary>
        internal static string KnownBug {
            get {
                return ResourceManager.GetString("KnownBug", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap norecord {
            get {
                object obj = ResourceManager.GetObject("norecord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap record {
            get {
                object obj = ResourceManager.GetObject("record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 refresh &quot;{0}&quot;page 的本地化字符串。
        /// </summary>
        internal static string RefreshComment {
            get {
                return ResourceManager.GetString("RefreshComment", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 select &quot;{2}&quot; in &quot;{1}&quot; of &quot;{0}&quot; page 的本地化字符串。
        /// </summary>
        internal static string SelectComment {
            get {
                return ResourceManager.GetString("SelectComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 input &quot;{2}&quot; in &quot;{1}&quot; of &quot;{0}&quot; page 的本地化字符串。
        /// </summary>
        internal static string SendKeysComment {
            get {
                return ResourceManager.GetString("SendKeysComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An HTML Dialog cannot be tracked by this application.
        ///If you know someone at Microsoft who can change this, we&apos;d love to support it. (MSDN KB251128)
        ///
        ///Continue opening the page? 的本地化字符串。
        /// </summary>
        internal static string showDialogBug {
            get {
                return ResourceManager.GetString("showDialogBug", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 validate alert&apos;s text 的本地化字符串。
        /// </summary>
        internal static string ValidateAlertText {
            get {
                return ResourceManager.GetString("ValidateAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 validate page&apos;s title 的本地化字符串。
        /// </summary>
        internal static string ValidateBrowserTitle {
            get {
                return ResourceManager.GetString("ValidateBrowserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 validate page&apos;s url 的本地化字符串。
        /// </summary>
        internal static string ValidateBrowserUrl {
            get {
                return ResourceManager.GetString("ValidateBrowserUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 validate image 的本地化字符串。
        /// </summary>
        internal static string ValidateImage {
            get {
                return ResourceManager.GetString("ValidateImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 validate element text 的本地化字符串。
        /// </summary>
        internal static string ValidateItemText {
            get {
                return ResourceManager.GetString("ValidateItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 validate element value 的本地化字符串。
        /// </summary>
        internal static string ValidateItemValue {
            get {
                return ResourceManager.GetString("ValidateItemValue", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap xls {
            get {
                object obj = ResourceManager.GetObject("xls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
